### ISSUE TITLE
Open hardware design files

### ISSUE THREAD

**Issue by samuk** [ochin-space/ochin-CM4#7]
I see you use the open hardware logo, but I don't see the hardware files Kicad etc are they in a separate repo?

**Comment by pernicious-flier** [comment]
> 

Hello samuk, i've already explained in other places the reason why i didn't share the kicad files, I'll explain it again once and for all.
The reason lies in the fact that the production of a single piece does not make any sense due to the very high production and assembly costs. It is also not the type of board that can be assembled by hand in a hobbyist workshop. It is in fact required the assembly of components that are difficult to handle and weld, delicate and for which a high positioning accuracy is also required (an example for all is the positioning of the mezzanines). 
For those wishing to understand and learn about my project, the schematics are available in this repo and at the end of the manual there are the images of the 4-layer pcb. 
Making the kicad files and therefore the gerber files available, means nothing for those who are really interested in the project, as I said it is much more expensive to build it than to buy it, and the only way to lower costs is to produce as many boards as possible, but this it is a self-financed project.
Gerbers could be of interest to those who have the opportunity to produce a big number of ochin_CM4 boards without initial investment, hours and hours of design, document, tests, debug, prototypes and marketing ... in short, only profits without work and risks. Probably this would allow, initially, to lower the price by a few euros, but it would kill this project forever and I don't want that to happen.
On the contrary, I would like to continue with the development, listening to your needs and talking with the developers of other beautiful open projects such as OpenHD in order to improve the board. 
By the way, the Raspberry Pi provides the kicad sources of the IO board, which includes what is contained in the ochin and much more. In the ochin_CM4 board I used slightly different components and the power section it is completely different, but theoretically they are very similar.
If anyone has technical questions that I can answer, I will be happy to do so. 
Hope you can understand, Flavio

**Comment by samuk** [comment]
Hi Flavio

That's fine, it makes sense. 

My only issue is with your use of the Open hardware logo & branding. https://www.oshwa.org/open-source-hardware-logo/ Your board does not meet the open hardware definition. If you removed those from your board design it would be clear to everyone that this is not an open hardware product.

You might find you have to explain it less often then.

**Comment by pernicious-flier** [comment]
> Hi Flavio
> 
> That's fine, it makes sense.
> 
> My only issue is with your use of the Open hardware logo & branding. https://www.oshwa.org/open-source-hardware-logo/ Your board does not meet the open hardware definition. If you removed those from your board design it would be clear to everyone that this is not an open hardware product.
> 
> You might find you have to explain it less often then.

You're right samuk, my fault. I thought it was enough to provide the documentation but the license is very clear about the sources. I will remove the logo from the design. 
Thanks, Flavio

**Comment by samuk** [comment]
No worries, I don't mean to be a dick about it. It does look like a nice board..

**Comment by pernicious-flier** [comment]
Ha ha, no worries, it's  a good advice!

**Comment by pernicious-flier** [comment]
OSHW logo removed, 
but I want to write to the Oshw guys because in my opinion my motivations are solid. My project contains all the information to understand and possibly replicate the board, more information than is normally found in other oshw projects (manuals, description of the hw tests carried out, wiring tips etc ..). Therefore, in my opinion, the dissemination function is fully fulfilled. The sources are missing for the reasons I explained, mainly to protect the project (which the oshw license does not do). I think they should create another level of license, which requires the complete description of the electronics without sharing the sources. Obviously this problem does not exist for open source software, which does not require production costs.
What do you think?

**Comment by samuk** [comment]
I'm not an expert. The boards I've been involved with have all been released under an open hardware licence: https://github.com/rosmo-robot/

My interest in your board was as a carrier for https://github.com/antmicro/arvsom this would have fitted in with the 'Open hardware' brand of Rosmo. I might have made a few minor alterations to your board: An extra Qwiic socket and perhaps a 5pin breakout garden I2C. I don't want to, nor have the skills to re-engineer the whole thing from scratch. So for my (particular) interest, your board is no longer helpful to me. No matter how good the documentation. I'll probably use something like https://github.com/samuk/CM4-Header-Gigabit-2xCam instead.

**Comment by pernicious-flier** [comment]
> I'm not an expert. The boards I've been involved with have all been released under an open hardware licence: https://github.com/rosmo-robot/
> 
> My interest in your board was as a carrier for https://github.com/antmicro/arvsom this would have fitted in with the 'Open hardware' brand of Rosmo. I might have made a few minor alterations to your board: An extra Qwiic socket and perhaps a 5pin breakout garden I2C. I don't want to, nor have the skills to re-engineer the whole thing from scratch. So for my (particular) interest, your board is no longer helpful to me. No matter how good the documentation. I'll probably use something like https://github.com/samuk/CM4-Header-Gigabit-2xCam instead.

I get it, but trust me that modifying the board means redoing part or all of the layout, which is the tricky part. If you don't know how to deal with fast signals, track impedance, differential pairs, and ground planes, nothing will work. I encourage you to delve into these topics before modifying such a card.
Greetings, Flavio
